# Generated by Django 4.1.3 on 2022-12-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Image', models.ImageField(blank=True, default='media/media/me.jpg', null=True, upload_to='media/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Description', models.TextField(max_length=2000)),
                ('Type', models.CharField(blank=True, choices=[('Web Design', 'Web Design'), ('Web Development', 'Web Development'), ('Computer Vision', 'Computer Vision'), ('Automation', 'Automation')], max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Image', models.ImageField(blank=True, default='media/media/me.jpg', null=True, upload_to='media/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Type', models.CharField(blank=True, choices=[('Web Design', 'Web Design'), ('Web Development', 'Web Development'), ('Computer Vision', 'Computer Vision'), ('Automation', 'Automation')], max_length=1000, null=True)),
            ],
        ),
    ]
