# Generated by Django 4.1.3 on 2022-12-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Type',
            field=models.CharField(blank=True, choices=[('web design', 'web design'), ('web development', 'web development'), ('computer vision', 'computer vision'), ('automation', 'automation')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='Type',
            field=models.CharField(blank=True, choices=[('web design', 'web design'), ('web development', 'web development'), ('computer vision', 'computer vision'), ('automation', 'automation')], max_length=1000, null=True),
        ),
    ]
