# Generated by Django 4.1.3 on 2022-12-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_blog_link_alter_blog_type_alter_portfolio_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('message', models.TextField(max_length=2000)),
                ('phone', models.CharField(default='+255', max_length=1000)),
                ('place', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
